### ISSUE TITLE
Move workspace indexing from vscode client

### ISSUE THREAD

**Issue by bmewburn** [bmewburn/intelephense-server#1]
Will need an implementation of `workspace.findFiles`. Consider spawning node separate process to do indexing.

**Comment by carlevison** [comment]
@bmewburn Any updates on this? Thanks.

**Comment by mikebronner** [comment]
Hi @bmewburn , we talked quite a while back about this being a requirement for me creating an auto-complete-language server for the Atom editor. Have you been able to make any progress on this? The auto-complete options for PHP in Atom are really horrible, and I would like to get yours implemented. :) Sorry to bug you ... I would offer to help, but I don't think I have the knowledge necessary to make your life easier, unfortunately.

**Comment by carlevison** [comment]
@mikebronner I spoke to Ben around the 5th and he told me that he'd taken a break from the project but recently started working on it again in a private repo and hopes to release it soon.

hopefully @bmewburn can shed some light on how it's going.

**Comment by mikebronner** [comment]
Thanks for the update @carlevison! @bmewburn, wishing you the best. Looking forward to your work.

**Comment by bmewburn** [comment]
@mikebronner, making progress, hope to have something soon.

**Comment by bmewburn** [comment]
resolved in 1.0

**Comment by marlonfan** [comment]
not find this version?

**Comment by josecanciani** [comment]
Great news! Can't wait to start using it. Can you tag a release, or do you still have things to fix in 1.0?
BTW: Patreon doesn't allow a one time pay right? :)

**Comment by jfcherng** [comment]
@josecanciani It's now https://github.com/bmewburn/intelephense-docs I guess.

**Comment by bmewburn** [comment]
@josecanciani I've closed the source for this version. It's available on npm under `intelephense`. There's a few fixes to come.

**Comment by josecanciani** [comment]
oh, I was waiting for intelephense-server 1.0 :)

```
joe@joseca:~$ sudo npm install -g intelephense-server intelephense
[sudo] password for joe: 
/usr/bin/intelephense -> /usr/lib/node_modules/intelephense/lib/intelephense.js
+ intelephense-server@0.8.8
+ intelephense@1.0.2
updated 2 packages in 8.765s
```
