### ISSUE TITLE
Parser not recovering from incomplete line.

### ISSUE THREAD

**Issue by mikebronner** [bmewburn/intelephense-server#3]
Ben wrote in #2:

> Secondly, I think the parser is not recovering properly from the below error which means that methods declared after this error are not being read.
```php
$this-> //this is being read as an if method
if($a && $b) { }
```
> So there's a couple of things that need to be improved in this library.

**Comment by bmewburn** [comment]
Hi @mikebronner , will close this as I have a fix for this in the parser repo now. Still some work to do to get the new parser adopted into the main library. Thanks for troubleshooting.

**Comment by mikebronner** [comment]
Heya @bmewburn, thanks! Anxiously awaiting the update so I can continue implementation. :) Do you have an issue I can track this on to get an update when you have it in place?

**Comment by bmewburn** [comment]
The workspace indexing ticket is the main one that needs to be resolved.
