### ISSUE TITLE
Use `bin` field in package.json so server is available on $PATH

### ISSUE THREAD

**Issue by bigsweater** [bmewburn/intelephense-server#4]
Using this server with [LSP on Sublime](https://github.com/tomv564/LSP) works well! 

However, I currently have to reference the exact path of `server.js` in my LSP config:

```json
"command":
[
	"node",
	"/really/long/path/because/nvm/node_modules/intelephense-server/lib/server.js",
	"--stdio"
],
```

It'd be great if this package used the [`bin` field](https://docs.npmjs.com/files/package.json#bin) in `package.json` so the server is a little more portable. When I upgrade Node via nvm, that path is going to change, and I'm **definitely** going to forget to update it in my Sublime config.

[Similar setup in the js/ts langserver](https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/package.json#L89-L92), for reference.

**Comment by bmewburn** [comment]
resolved in 1.0. Executable is named `intelephense`.
