### ISSUE TITLE
How to use this in emacs?

### ISSUE THREAD

**Issue by zbelial** [bmewburn/intelephense-server#5]
It seems that this is very good, and I wish it can be used in emacs, and I think it's possible, so
could you give me some advice on how to use it in emacs(I use lsp-mode [lsp-mode](https://github.com/emacs-lsp/lsp-mode) )

Actually, I haved tried to use it in emacs as follows
1 I cloned this project and built it using the command: npm build
2 then I wrote a lsp-mode client, which starts intelephense-server using the command:
   node /absolute/path/to/intelephense-server/lib/server.js --stdio

But when I opened a php file, intelephense-server reported some errors such as "Cannot read property ’storagePath’ of null ".

Thanks.

**Comment by bmewburn** [comment]
Thanks for your interest. You need to pass an `initializationOptions` object with a `storagePath` string with with the `initialize` request. https://microsoft.github.io/language-server-protocol/specification#initialize

This will be made optional in the next release to match the spec. Note that workspace indexing is not available yet server side (#1) so it will only index the files you open.

**Comment by zbelial** [comment]
Thank you for providing these information. I'll read the spec and try to create a lsp client for emacs. But I'm not familiar with nodejs and lsp protocol, so It may not be successful, haha.
Thanks again.

**Comment by Gleek** [comment]
For anyone stumbling on this. You can do:
```elisp
(lsp-define-stdio-client lsp-php "php"
                         'lsp-php-get-root
                         (lsp-php-get-language-server-command)
                         :ignore-regexps (lsp-php-get-ignore-regexps)
                         :extra-init-params '(:storagePath "a/valid/path/.intelliphense/"))
```
in the existing [lsp-php](https://github.com/emacs-lsp/lsp-php/).
But as @bmewburn mentioned this would work only on the file you open and not on the complete project.

**Comment by bmewburn** [comment]
all init params are now optional in 1.0
